import UserService from "@repo/services/user";
import AuthService from "@repo/services/auth";
import VisitorService from "@repo/services/visitor";
import ResidentService from "@repo/services/resident";
import TowerService from "@repo/services/tower";
import FlatService from "@repo/services/flat";
import AmenityService from "@repo/services/amenity";
import NoticeService from "@repo/services/notice";
import PollService from "@repo/services/poll";
import ComplaintService from "@repo/services/complaint";
import StaffDirectoryService from "@repo/services/staff-directory";
import AdminService from "@repo/services/admin";
import NotificationService from "@repo/services/notification";
import AmenityBookingService from "@repo/services/amenity-booking";
import DueService from "@repo/services/due";
import PushTokenService from "@repo/services/push-token";
import PostService from "@repo/services/post";
import ServiceRequestService from "@repo/services/service-request";
import ChatService from "@repo/services/chat";

export const userService = new UserService();
export const authService = new AuthService();
export const visitorService = new VisitorService();
export const residentService = new ResidentService();
export const towerService = new TowerService();
export const flatService = new FlatService();
export const amenityService = new AmenityService();
export const noticeService = new NoticeService();
export const pollService = new PollService();
export const complaintService = new ComplaintService();
export const staffDirectoryService = new StaffDirectoryService();
export const adminService = new AdminService();
export const notificationService = new NotificationService();
export const amenityBookingService = new AmenityBookingService();
export const dueService = new DueService();
export const pushTokenService = new PushTokenService();
export const postService = new PostService();
export const serviceRequestService = new ServiceRequestService();
export const chatService = new ChatService();
