import UserService from "@repo/services/user";
import AuthService from "@repo/services/auth";
import VisitorService from "@repo/services/visitor";
import ResidentService from "@repo/services/resident";
import TowerService from "@repo/services/tower";
import FlatService from "@repo/services/flat";
import AmenityService from "@repo/services/amenity";
import NoticeService from "@repo/services/notice";
import PollService from "@repo/services/poll";
import ComplaintService from "@repo/services/complaint";
import StaffDirectoryService from "@repo/services/staff-directory";
import AdminService from "@repo/services/admin";
import NotificationService from "@repo/services/notification";

export const userService = new UserService();
export const authService = new AuthService();
export const visitorService = new VisitorService();
export const residentService = new ResidentService();
export const towerService = new TowerService();
export const flatService = new FlatService();
export const amenityService = new AmenityService();
export const noticeService = new NoticeService();
export const pollService = new PollService();
export const complaintService = new ComplaintService();
export const staffDirectoryService = new StaffDirectoryService();
export const adminService = new AdminService();
